# Generated by Django 3.1.7 on 2021-03-31 07:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20210319_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_az',
            field=models.CharField(max_length=127, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=127, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=127, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Mezmun'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Mezmun'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Mezmun'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_description_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Qisa Mezmun'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Qisa Mezmun'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Qisa Mezmun'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug_az',
            field=models.SlugField(max_length=155, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug_en',
            field=models.SlugField(max_length=155, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug_ru',
            field=models.SlugField(max_length=155, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_az',
            field=models.CharField(max_length=127, null=True, verbose_name='Basliq'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_en',
            field=models.CharField(max_length=127, null=True, verbose_name='Basliq'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_ru',
            field=models.CharField(max_length=127, null=True, verbose_name='Basliq'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_az',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(max_length=155, verbose_name='Slug'),
        ),
    ]
