version: '3.1'

services:
    redis_service:
        image: redis
        ports: 
            - "6380:6379"
        volumes: 
            - ./redisdb:/data

    web:
        build: .
        container_name: 'flask_application'
        ports: 
            - "5050:5000"
        command: flask run --host 0.0.0.0 -p 5000
        environment: 
            - FLASK_APP=main.py
        depends_on: 
            - "redis_service"
            - "db"

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
    
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    