version: '3.1'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/vhost/:/etc/nginx/vhost.d:ro
      - ./nginx/conf.d/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
      - ./static/:/myfiles/static
      - ./media/:/myfiles/media

  postgres:
        image: postgres
        volumes:
            - ./pgdb/:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        env_file: ./.env

  web:
      build: .
      volumes:
        - .:/code
        - ./static/:/code/static
        - ./media/:/code/media
      ports:
        - "8000:8000"
      depends_on:
        - "postgres"
      env_file: ./.env

  celery:
    build:
      context: .
      dockerfile: celery.dockerfile
    volumes:
      - .:/code
      - ./static/:/code/static
      - ./media/:/code/media
    command: celery -A food_stories worker --beat --scheduler django --loglevel=info
    depends_on:
      - "postgres"
      - "redis"
    env_file: ./.env


#    adminer:
#      image: adminer
#      restart: always
#      ports:
#        - 8080:8080

  redis:
      image: redis
      restart: always
      ports:
        - 6379:6379